# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\39772\Desktop\first.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(661, 314)
        Dialog.setMinimumSize(QtCore.QSize(661, 314))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 591, 131))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.left = QtWidgets.QPushButton(Dialog)
        self.left.setGeometry(QtCore.QRect(120, 190, 181, 28))
        self.left.setObjectName("left")
        self.right = QtWidgets.QPushButton(Dialog)
        self.right.setGeometry(QtCore.QRect(380, 190, 211, 28))
        self.right.setObjectName("right")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "System"))
        self.label.setText(_translate("Dialog", "注水管道及站场风险评价软件"))
        self.left.setText(_translate("Dialog", "泵站及配水间风险评价"))
        self.right.setText(_translate("Dialog", "注水管道风险评价"))
