# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\39772\Desktop\ui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(615, 707)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        self.label_1 = QtWidgets.QLabel(Dialog)
        self.label_1.setGeometry(QtCore.QRect(150, 140, 128, 16))
        self.label_1.setObjectName("label_1")
        self.factor = QtWidgets.QTextBrowser(Dialog)
        self.factor.setGeometry(QtCore.QRect(150, 430, 311, 171))
        self.factor.setObjectName("factor")
        self.begin_button = QtWidgets.QPushButton(Dialog)
        self.begin_button.setGeometry(QtCore.QRect(380, 130, 81, 28))
        self.begin_button.setObjectName("begin_button")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(150, 320, 158, 16))
        self.label_3.setObjectName("label_3")
        self.ensure_button = QtWidgets.QPushButton(Dialog)
        self.ensure_button.setGeometry(QtCore.QRect(380, 320, 81, 28))
        self.ensure_button.setObjectName("ensure_button")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(150, 360, 158, 16))
        self.label_4.setObjectName("label_4")
        self.change_result_text = QtWidgets.QTextBrowser(Dialog)
        self.change_result_text.setGeometry(QtCore.QRect(380, 360, 81, 31))
        self.change_result_text.setObjectName("change_result_text")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(150, 400, 261, 16))
        self.label_5.setObjectName("label_5")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(150, 170, 311, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.result_text = QtWidgets.QTextBrowser(self.formLayoutWidget)
        self.result_text.setObjectName("result_text")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.result_text)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.result2_text = QtWidgets.QTextBrowser(self.formLayoutWidget)
        self.result2_text.setObjectName("result2_text")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.result2_text)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.result3_text = QtWidgets.QTextBrowser(self.formLayoutWidget)
        self.result3_text.setObjectName("result3_text")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.result3_text)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.result1_text = QtWidgets.QTextBrowser(self.formLayoutWidget)
        self.result1_text.setObjectName("result1_text")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.result1_text)
        self.file_button = QtWidgets.QPushButton(Dialog)
        self.file_button.setGeometry(QtCore.QRect(150, 40, 141, 41))
        self.file_button.setObjectName("file_button")
        self.filename = QtWidgets.QTextBrowser(Dialog)
        self.filename.setGeometry(QtCore.QRect(300, 40, 161, 41))
        self.filename.setObjectName("filename")
        self.file_ensure_buttom = QtWidgets.QPushButton(Dialog)
        self.file_ensure_buttom.setGeometry(QtCore.QRect(180, 90, 93, 28))
        self.file_ensure_buttom.setObjectName("file_ensure_buttom")
        self.file_cancel_buttom = QtWidgets.QPushButton(Dialog)
        self.file_cancel_buttom.setGeometry(QtCore.QRect(320, 90, 93, 28))
        self.file_cancel_buttom.setObjectName("file_cancel_buttom")
        self.result_button = QtWidgets.QPushButton(Dialog)
        self.result_button.setGeometry(QtCore.QRect(370, 620, 93, 28))
        self.result_button.setObjectName("result_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "泵站及配水间风险评价系统"))
        self.label_1.setText(_translate("Dialog", "点击按钮开始评测:"))
        self.factor.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.begin_button.setText(_translate("Dialog", "开始"))
        self.label_3.setText(_translate("Dialog", "是否采取措施降低风险:"))
        self.ensure_button.setText(_translate("Dialog", "是"))
        self.label_4.setText(_translate("Dialog", "采取措施后评测结果为:"))
        self.label_5.setText(_translate("Dialog", "建议采取措施为:"))
        self.label_2.setText(_translate("Dialog", "评测结果:"))
        self.label_6.setText(_translate("Dialog", "设备因素"))
        self.label_7.setText(_translate("Dialog", "环境因素"))
        self.label.setText(_translate("Dialog", "管理,人为因素"))
        self.file_button.setText(_translate("Dialog", "点击按钮选择文件"))
        self.file_ensure_buttom.setText(_translate("Dialog", "确认"))
        self.file_cancel_buttom.setText(_translate("Dialog", "取消"))
        self.result_button.setText(_translate("Dialog", "导出结果"))
